version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: contactos-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: contactos_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d contactos_db"]
      interval: 10s
      timeout: 5s
      retries: 5
